[
   ParserRule                -- _1 _2 KW[":"] KW[";"],
   Returns                   -- KW["returns"] _1,
   None                      -- ,
   MetaModel                 -- _1 _2 _3,
   MetaModel.2:ci-lit        -- _1,
   MetaModel.2:ci-lit.1:"::" -- ,
   Classifier                -- _1,
   Optional                  -- KW["?"],
   Multiple                  -- KW["+"],
   Any                       -- KW["*"],
   COMPLETION-Cardinality    -- _1,
   Grammar                   -- KW["grammar"] _1 _2 _3,
   Grammar.1:iter-sep        -- _1 KW["."],
   Grammar.3:iter            -- _1,
   GrammarId                 -- _1,
   GrammarId.1:iter-sep      -- _1 KW["."],
   None                      -- ,
   Mixin                     -- V  [H  [KW["with"]] _1],
   Mixin.1:iter-sep          -- _1 KW[","],
   COMPLETION-Start          -- _1,
   COMPLETION-GrammarId      -- _1,
   COMPLETION-Mixin          -- _1
]